server:
  port: 8080
  servlet:
    session:
      timeout: 1800 # 세션 유효 시간 30분 (단위: 초)
      cookie:
        http-only: true   # HttpOnly 플래그 활성화
        secure: true       # Secure 플래그 활성화 (HTTPS 환경에서만 작동)

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/db_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sa
    password: 1234

  thymeleaf:
    cache: false
    prefix: classpath:/templates/   # 배포시 경로
##    prefix: file:src/main/resources/templates/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update